### ISSUE TITLE
proxy support improvements

### ISSUE THREAD

**Issue by pi0** [unjs/node-fetch-native#107]
[Docs](https://github.com/unjs/node-fetch-native?tab=readme-ov-file#proxy-support)

Nice article: https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/

```[tasklist]
### Tasks
- [x] Initial support (#106)
- [x] preconfigured `fetch` export from `/proxy` (#108)
- [x] Support `NO_PROXY` environment variable (#109)
- [ ] ~~Reduce bundle size by removing HTTP parser wasm~~
```

**Comment by CS-JJ** [comment]
the [bypassProxy](https://github.com/unjs/node-fetch-native/blob/main/src/proxy.ts#L21) implementation doesn't check for port specification. Currently there is a workaround by just specifying the port in the no_proxy host declaration.

Can be checked using the following 
```
if (_host === host.split(":").at(0) || (_host[0] === "." && host.endsWith(_host.slice(1)))) {
```
Or if you want to save CPU cycles just over write the host parameter
```
host = host.split(':').at(0);
```

**Comment by pi0** [comment]
@CS-JJ Would you please make a new issue with proper reproduction? 🙏🏼
